#-------------------------------------------------
#
# Project created by QtCreator 2014-07-12T15:20:14
#
#-------------------------------------------------

QT       += core gui widgets opengl

TARGET = luna2d
TEMPLATE = lib
CONFIG += staticlib c++11
DEFINES += FT2_BUILD_LIBRARY

QMAKE_CFLAGS_WARN_ON -= -Wextra
QMAKE_CXXFLAGS_WARN_ON -= -Wextra

QMAKE_CFLAGS_WARN_ON += -Werror=return-type
QMAKE_CXXFLAGS_WARN_ON += -Werror=return-type

CONFIG(debug, debug|release) {
	DESTDIR = $$PWD/../../../lib/qt/debug/
}

CONFIG(release, debug|release) {
	DESTDIR = $$PWD/../../../lib/qt/release/
}

INCLUDEPATH += ../../../luna2d \
	../../../luna2d/assets/ \
	../../../luna2d/graphics/ \
	../../../luna2d/lua/ \
	../../../luna2d/physics/ \
	../../../luna2d/modules/ \
	../../../luna2d/utils/ \
	../../../luna2d/utils/math/ \
	../../../luna2d/platform/ \
	../../../luna2d/platform/qt/ \
	../../../luna2d/thirdparty/ \
	../../../luna2d/thirdparty/lua/ \
	../../../luna2d/thirdparty/libpng/ \
	../../../luna2d/thirdparty/json11/ \
	../../../luna2d/thirdparty/Box2D/ \
	../../../luna2d/thirdparty/freetype/devel/ \
	../../../luna2d/thirdparty/freetype/include/ \
	../../../luna2d/thirdparty/utf8cpp/

SOURCES += \
    ../../../luna2d/graphics/lunagraphics.cpp \
    ../../../luna2d/graphics/lunaimage.cpp \
    ../../../luna2d/graphics/lunapngformat.cpp \
    ../../../luna2d/graphics/lunarenderer.cpp \
    ../../../luna2d/graphics/lunashader.cpp \
    ../../../luna2d/graphics/lunatexture.cpp \
    ../../../luna2d/lua/luafunction.cpp \
    ../../../luna2d/lua/luaref.cpp \
    ../../../luna2d/lua/luascript.cpp \
    ../../../luna2d/lua/luatable.cpp \
    ../../../luna2d/platform/qt/lunaqtwidget.cpp \
    ../../../luna2d/utils/lunacolor.cpp \
	../../../luna2d/assets/lunaassets.cpp \
    ../../../luna2d/lunaengine.cpp \
    ../../../luna2d/lunascenes.cpp \
	../../../luna2d/thirdparty/libpng/png.c \
	../../../luna2d/thirdparty/libpng/pngerror.c \
	../../../luna2d/thirdparty/libpng/pngget.c \
	../../../luna2d/thirdparty/libpng/pngmem.c \
	../../../luna2d/thirdparty/libpng/pngpread.c \
	../../../luna2d/thirdparty/libpng/pngread.c \
	../../../luna2d/thirdparty/libpng/pngrio.c \
	../../../luna2d/thirdparty/libpng/pngrtran.c \
	../../../luna2d/thirdparty/libpng/pngrutil.c \
	../../../luna2d/thirdparty/libpng/pngset.c \
	../../../luna2d/thirdparty/libpng/pngtrans.c \
	../../../luna2d/thirdparty/libpng/pngwio.c \
	../../../luna2d/thirdparty/libpng/pngwrite.c \
	../../../luna2d/thirdparty/libpng/pngwtran.c \
	../../../luna2d/thirdparty/libpng/pngwutil.c \
    ../../../luna2d/thirdparty/lua/lapi.c \
    ../../../luna2d/thirdparty/lua/lauxlib.c \
    ../../../luna2d/thirdparty/lua/lbaselib.c \
    ../../../luna2d/thirdparty/lua/lbitlib.c \
    ../../../luna2d/thirdparty/lua/lcode.c \
    ../../../luna2d/thirdparty/lua/lcorolib.c \
    ../../../luna2d/thirdparty/lua/lctype.c \
    ../../../luna2d/thirdparty/lua/ldblib.c \
    ../../../luna2d/thirdparty/lua/ldebug.c \
    ../../../luna2d/thirdparty/lua/ldo.c \
    ../../../luna2d/thirdparty/lua/ldump.c \
    ../../../luna2d/thirdparty/lua/lfunc.c \
    ../../../luna2d/thirdparty/lua/lgc.c \
    ../../../luna2d/thirdparty/lua/linit.c \
    ../../../luna2d/thirdparty/lua/liolib.c \
    ../../../luna2d/thirdparty/lua/llex.c \
    ../../../luna2d/thirdparty/lua/lmathlib.c \
    ../../../luna2d/thirdparty/lua/lmem.c \
    ../../../luna2d/thirdparty/lua/loadlib.c \
    ../../../luna2d/thirdparty/lua/lobject.c \
    ../../../luna2d/thirdparty/lua/lopcodes.c \
    ../../../luna2d/thirdparty/lua/loslib.c \
    ../../../luna2d/thirdparty/lua/lparser.c \
    ../../../luna2d/thirdparty/lua/lstate.c \
    ../../../luna2d/thirdparty/lua/lstring.c \
    ../../../luna2d/thirdparty/lua/lstrlib.c \
    ../../../luna2d/thirdparty/lua/ltable.c \
    ../../../luna2d/thirdparty/lua/ltablib.c \
    ../../../luna2d/thirdparty/lua/ltm.c \
    ../../../luna2d/thirdparty/lua/lundump.c \
    ../../../luna2d/thirdparty/lua/lvm.c \
    ../../../luna2d/thirdparty/lua/lzio.c \
    ../../../luna2d/lunaconfig.cpp \
    ../../../luna2d/lunasizes.cpp \
    ../../../luna2d/graphics/lunatextureregion.cpp \
    ../../../luna2d/graphics/lunatextureatlas.cpp \
    ../../../luna2d/graphics/lunasprite.cpp \
    ../../../luna2d/thirdparty/json11/json11.cpp \
    ../../../luna2d/utils/lunawatcher.cpp \
    ../../../luna2d/lua/luadynamictype.cpp \
    ../../../luna2d/graphics/lunamesh.cpp \
    ../../../luna2d/lua/luaobject.cpp \
    ../../../luna2d/physics/lunaphysicsmodule.cpp \
    ../../../luna2d/physics/lunaphysicsworld.cpp \
    ../../../luna2d/thirdparty/Box2D/Collision/Shapes/b2ChainShape.cpp \
    ../../../luna2d/thirdparty/Box2D/Collision/Shapes/b2CircleShape.cpp \
    ../../../luna2d/thirdparty/Box2D/Collision/Shapes/b2EdgeShape.cpp \
    ../../../luna2d/thirdparty/Box2D/Collision/Shapes/b2PolygonShape.cpp \
    ../../../luna2d/thirdparty/Box2D/Collision/b2BroadPhase.cpp \
    ../../../luna2d/thirdparty/Box2D/Collision/b2CollideCircle.cpp \
    ../../../luna2d/thirdparty/Box2D/Collision/b2CollideEdge.cpp \
    ../../../luna2d/thirdparty/Box2D/Collision/b2CollidePolygon.cpp \
    ../../../luna2d/thirdparty/Box2D/Collision/b2Collision.cpp \
    ../../../luna2d/thirdparty/Box2D/Collision/b2Distance.cpp \
    ../../../luna2d/thirdparty/Box2D/Collision/b2DynamicTree.cpp \
    ../../../luna2d/thirdparty/Box2D/Collision/b2TimeOfImpact.cpp \
    ../../../luna2d/thirdparty/Box2D/Common/b2BlockAllocator.cpp \
    ../../../luna2d/thirdparty/Box2D/Common/b2Draw.cpp \
    ../../../luna2d/thirdparty/Box2D/Common/b2Math.cpp \
    ../../../luna2d/thirdparty/Box2D/Common/b2Settings.cpp \
    ../../../luna2d/thirdparty/Box2D/Common/b2StackAllocator.cpp \
    ../../../luna2d/thirdparty/Box2D/Common/b2Timer.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2Contact.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2GearJoint.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2Joint.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/b2Body.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/b2ContactManager.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/b2Fixture.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/b2Island.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/b2World.cpp \
    ../../../luna2d/thirdparty/Box2D/Dynamics/b2WorldCallbacks.cpp \
    ../../../luna2d/thirdparty/Box2D/Rope/b2Rope.cpp \
    ../../../luna2d/physics/lunaphysicsbody.cpp \
    ../../../luna2d/physics/lunaphysicsfixture.cpp \
    ../../../luna2d/physics/lunaphysicsdebugrenderer.cpp \
    ../../../luna2d/utils/lunaglhelpers.cpp \
    ../../../luna2d/physics/shapes/lunaphysicscircleshape.cpp \
    ../../../luna2d/physics/shapes/lunaphysicsedgeshape.cpp \
    ../../../luna2d/physics/shapes/lunaphysicsrectshape.cpp \
    ../../../luna2d/physics/shapes/lunaphysicsshape.cpp \
    ../../../luna2d/physics/joints/lunaphysicsjoint.cpp \
    ../../../luna2d/physics/joints/lunaphysicsdistancejoint.cpp \
    ../../../luna2d/physics/lunaphysicsutils.cpp \
    ../../../luna2d/platform/lunafiles.cpp \
    ../../../luna2d/platform/qt/lunaqtfiles.cpp \
    ../../../luna2d/platform/lunalog.cpp \
    ../../../luna2d/platform/qt/lunaqtlog.cpp \
    ../../../luna2d/platform/qt/lunaqtgl.cpp \
    ../../../luna2d/platform/lunaplatformutils.cpp \
    ../../../luna2d/graphics/lunacurverenderer.cpp \
    ../../../luna2d/assets/lunatextureloader.cpp \
    ../../../luna2d/assets/lunatextureatlasloader.cpp \
    ../../../luna2d/lunabindings.cpp \
    ../../../luna2d/utils/math/lunaintersect.cpp \
    ../../../luna2d/utils/math/lunasplines.cpp \
    ../../../luna2d/utils/math/lunavector2.cpp \
    ../../../luna2d/utils/math/lunamath.cpp \
    ../../../luna2d/lunadebug.cpp \
    ../../../luna2d/graphics/lunatext.cpp \
    ../../../luna2d/graphics/lunafont.cpp \
    ../../../luna2d/assets/lunafontloader.cpp \
	../../../luna2d/graphics/lunafontgenerator.cpp \
    ../../../luna2d/thirdparty/freetype/src/base/ftbase.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftbbox.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftbdf.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftbitmap.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftcid.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftdebug.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftgasp.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftglyph.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftgxval.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftinit.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftmm.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftotval.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftpatent.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftstroke.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftsynth.c \
    ../../../luna2d/thirdparty/freetype/src/base/fttype1.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftxf86.c \
    ../../../luna2d/thirdparty/freetype/src/bdf/bdf.c \
    ../../../luna2d/thirdparty/freetype/src/bzip2/ftbzip2.c \
    ../../../luna2d/thirdparty/freetype/src/cache/ftcache.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cff.c \
    ../../../luna2d/thirdparty/freetype/src/cid/type1cid.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvalid.c \
    ../../../luna2d/thirdparty/freetype/src/gzip/ftgzip.c \
    ../../../luna2d/thirdparty/freetype/src/lzw/ftlzw.c \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otvalid.c \
    ../../../luna2d/thirdparty/freetype/src/pcf/pcf.c \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfr.c \
    ../../../luna2d/thirdparty/freetype/src/psaux/psaux.c \
    ../../../luna2d/thirdparty/freetype/src/pshinter/pshinter.c \
    ../../../luna2d/thirdparty/freetype/src/psnames/psnames.c \
    ../../../luna2d/thirdparty/freetype/src/raster/raster.c \
    ../../../luna2d/thirdparty/freetype/src/sfnt/sfnt.c \
    ../../../luna2d/thirdparty/freetype/src/smooth/smooth.c \
    ../../../luna2d/thirdparty/freetype/src/truetype/truetype.c \
    ../../../luna2d/thirdparty/freetype/src/type1/type1.c \
    ../../../luna2d/thirdparty/freetype/src/type42/type42.c \
    ../../../luna2d/thirdparty/freetype/src/winfonts/winfnt.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/afangles.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/afblue.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/afcjk.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/afdummy.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/afglobal.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/afhints.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/afindic.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/aflatin.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/aflatin2.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/afloader.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/afmodule.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/afpic.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/afranges.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/afwarp.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/autofit.c \
    ../../../luna2d/thirdparty/freetype/src/autofit/hbshim.c \
    ../../../luna2d/thirdparty/freetype/src/base/basepic.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftadvanc.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftapi.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftcalc.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftdbgmem.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftfstype.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftgloadr.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftlcdfil.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftmac.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftobjs.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftoutln.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftpfr.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftpic.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftrfork.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftsnames.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftstream.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftsystem.c \
    ../../../luna2d/thirdparty/freetype/src/base/fttrigon.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftutil.c \
    ../../../luna2d/thirdparty/freetype/src/base/ftwinfnt.c \
    ../../../luna2d/thirdparty/freetype/src/base/md5.c \
    ../../../luna2d/thirdparty/freetype/src/bdf/bdfdrivr.c \
    ../../../luna2d/thirdparty/freetype/src/bdf/bdflib.c \
    ../../../luna2d/thirdparty/freetype/src/cache/ftcbasic.c \
    ../../../luna2d/thirdparty/freetype/src/cache/ftccache.c \
    ../../../luna2d/thirdparty/freetype/src/cache/ftccmap.c \
    ../../../luna2d/thirdparty/freetype/src/cache/ftcglyph.c \
    ../../../luna2d/thirdparty/freetype/src/cache/ftcimage.c \
    ../../../luna2d/thirdparty/freetype/src/cache/ftcmanag.c \
    ../../../luna2d/thirdparty/freetype/src/cache/ftcmru.c \
    ../../../luna2d/thirdparty/freetype/src/cache/ftcsbits.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2arrst.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2blues.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2error.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2font.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2ft.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2hints.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2intrp.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2read.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2stack.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cffcmap.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cffdrivr.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cffgload.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cffload.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cffobjs.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cffparse.c \
    ../../../luna2d/thirdparty/freetype/src/cff/cffpic.c \
    ../../../luna2d/thirdparty/freetype/src/cid/cidgload.c \
    ../../../luna2d/thirdparty/freetype/src/cid/cidload.c \
    ../../../luna2d/thirdparty/freetype/src/cid/cidobjs.c \
    ../../../luna2d/thirdparty/freetype/src/cid/cidparse.c \
    ../../../luna2d/thirdparty/freetype/src/cid/cidriver.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvbsln.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvcommn.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvfeat.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvfgen.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvjust.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvkern.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvlcar.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmod.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmort.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmort0.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmort1.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmort2.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmort4.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmort5.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmorx.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmorx0.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmorx1.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmorx2.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmorx4.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmorx5.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvopbd.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvprop.c \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvtrak.c \
    ../../../luna2d/thirdparty/freetype/src/gzip/adler32.c \
    ../../../luna2d/thirdparty/freetype/src/gzip/infblock.c \
    ../../../luna2d/thirdparty/freetype/src/gzip/infcodes.c \
    ../../../luna2d/thirdparty/freetype/src/gzip/inflate.c \
    ../../../luna2d/thirdparty/freetype/src/gzip/inftrees.c \
    ../../../luna2d/thirdparty/freetype/src/gzip/infutil.c \
    ../../../luna2d/thirdparty/freetype/src/gzip/zutil.c \
    ../../../luna2d/thirdparty/freetype/src/lzw/ftzopen.c \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otvbase.c \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otvcommn.c \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otvgdef.c \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otvgpos.c \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otvgsub.c \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otvjstf.c \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otvmath.c \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otvmod.c \
    ../../../luna2d/thirdparty/freetype/src/pcf/pcfdrivr.c \
    ../../../luna2d/thirdparty/freetype/src/pcf/pcfread.c \
    ../../../luna2d/thirdparty/freetype/src/pcf/pcfutil.c \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrcmap.c \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrdrivr.c \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrgload.c \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrload.c \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrobjs.c \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrsbit.c \
    ../../../luna2d/thirdparty/freetype/src/psaux/afmparse.c \
    ../../../luna2d/thirdparty/freetype/src/psaux/psauxmod.c \
    ../../../luna2d/thirdparty/freetype/src/psaux/psconv.c \
    ../../../luna2d/thirdparty/freetype/src/psaux/psobjs.c \
    ../../../luna2d/thirdparty/freetype/src/psaux/t1cmap.c \
    ../../../luna2d/thirdparty/freetype/src/psaux/t1decode.c \
    ../../../luna2d/thirdparty/freetype/src/pshinter/pshalgo.c \
    ../../../luna2d/thirdparty/freetype/src/pshinter/pshglob.c \
    ../../../luna2d/thirdparty/freetype/src/pshinter/pshmod.c \
    ../../../luna2d/thirdparty/freetype/src/pshinter/pshpic.c \
    ../../../luna2d/thirdparty/freetype/src/pshinter/pshrec.c \
    ../../../luna2d/thirdparty/freetype/src/psnames/psmodule.c \
    ../../../luna2d/thirdparty/freetype/src/psnames/pspic.c \
    ../../../luna2d/thirdparty/freetype/src/raster/ftraster.c \
    ../../../luna2d/thirdparty/freetype/src/raster/ftrend1.c \
    ../../../luna2d/thirdparty/freetype/src/raster/rastpic.c \
    ../../../luna2d/thirdparty/freetype/src/sfnt/pngshim.c \
    ../../../luna2d/thirdparty/freetype/src/sfnt/sfdriver.c \
    ../../../luna2d/thirdparty/freetype/src/sfnt/sfntpic.c \
    ../../../luna2d/thirdparty/freetype/src/sfnt/sfobjs.c \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttbdf.c \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttcmap.c \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttkern.c \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttload.c \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttmtx.c \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttpost.c \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttsbit.c \
    ../../../luna2d/thirdparty/freetype/src/smooth/ftgrays.c \
    ../../../luna2d/thirdparty/freetype/src/smooth/ftsmooth.c \
    ../../../luna2d/thirdparty/freetype/src/smooth/ftspic.c \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttdriver.c \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttgload.c \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttgxvar.c \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttinterp.c \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttobjs.c \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttpic.c \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttpload.c \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttsubpix.c \
    ../../../luna2d/thirdparty/freetype/src/type1/t1afm.c \
    ../../../luna2d/thirdparty/freetype/src/type1/t1driver.c \
    ../../../luna2d/thirdparty/freetype/src/type1/t1gload.c \
    ../../../luna2d/thirdparty/freetype/src/type1/t1load.c \
    ../../../luna2d/thirdparty/freetype/src/type1/t1objs.c \
    ../../../luna2d/thirdparty/freetype/src/type1/t1parse.c \
    ../../../luna2d/thirdparty/freetype/src/type42/t42drivr.c \
    ../../../luna2d/thirdparty/freetype/src/type42/t42objs.c \
    ../../../luna2d/thirdparty/freetype/src/type42/t42parse.c \
    ../../../luna2d/utils/lunautf.cpp \
    ../../../luna2d/platform/lunaprefs.cpp \
    ../../../luna2d/platform/qt/lunaqtprefs.cpp

HEADERS += \
    ../../../luna2d/graphics/shaders/default.frag.h \
    ../../../luna2d/graphics/shaders/default.vert.h \
	../../../luna2d/graphics/shaders/primitives.frag.h \
    ../../../luna2d/graphics/lunagraphics.h \
    ../../../luna2d/graphics/lunaimage.h \
    ../../../luna2d/graphics/lunaimageformat.h \
    ../../../luna2d/graphics/lunapngformat.h \
    ../../../luna2d/graphics/lunarenderer.h \
    ../../../luna2d/graphics/lunashader.h \
    ../../../luna2d/graphics/lunatexture.h \
    ../../../luna2d/lua/scripts/logtable.lua.h \
    ../../../luna2d/lua/scripts/oopsupport.lua.h \
    ../../../luna2d/lua/scripts/userdatapairs.lua.h \
    ../../../luna2d/lua/luaclass.h \
    ../../../luna2d/lua/luafunction.h \
    ../../../luna2d/lua/luaproxy.h \
    ../../../luna2d/lua/luaref.h \
    ../../../luna2d/lua/luascript.h \
    ../../../luna2d/lua/luastack.h \
    ../../../luna2d/lua/luatable.h \
    ../../../luna2d/lua/lunalua.h \
    ../../../luna2d/modules/lunamodule.h \
    ../../../luna2d/modules/lunamoduleslist.h \
    ../../../luna2d/platform/qt/lunaqtwidget.h \
    ../../../luna2d/platform/lunafiles.h \
    ../../../luna2d/platform/lunagl.h \
    ../../../luna2d/platform/lunalog.h \
    ../../../luna2d/platform/lunaplatform.h \
    ../../../luna2d/platform/lunaplatformutils.h \
	../../../luna2d/thirdparty/libpng/config.h \
	../../../luna2d/thirdparty/libpng/png.h \
	../../../luna2d/thirdparty/libpng/pngconf.h \
	../../../luna2d/thirdparty/libpng/pngpriv.h \
    ../../../luna2d/thirdparty/lua/lapi.h \
    ../../../luna2d/thirdparty/lua/lauxlib.h \
    ../../../luna2d/thirdparty/lua/lcode.h \
    ../../../luna2d/thirdparty/lua/lctype.h \
    ../../../luna2d/thirdparty/lua/ldebug.h \
    ../../../luna2d/thirdparty/lua/ldo.h \
    ../../../luna2d/thirdparty/lua/lfunc.h \
    ../../../luna2d/thirdparty/lua/lgc.h \
    ../../../luna2d/thirdparty/lua/llex.h \
    ../../../luna2d/thirdparty/lua/llimits.h \
    ../../../luna2d/thirdparty/lua/lmem.h \
    ../../../luna2d/thirdparty/lua/lobject.h \
    ../../../luna2d/thirdparty/lua/lopcodes.h \
    ../../../luna2d/thirdparty/lua/lparser.h \
    ../../../luna2d/thirdparty/lua/lstate.h \
    ../../../luna2d/thirdparty/lua/lstring.h \
    ../../../luna2d/thirdparty/lua/ltable.h \
    ../../../luna2d/thirdparty/lua/ltm.h \
    ../../../luna2d/thirdparty/lua/lua.h \
    ../../../luna2d/thirdparty/lua/lua.hpp \
    ../../../luna2d/thirdparty/lua/luaconf.h \
    ../../../luna2d/thirdparty/lua/lualib.h \
    ../../../luna2d/thirdparty/lua/lundump.h \
    ../../../luna2d/thirdparty/lua/lvm.h \
    ../../../luna2d/thirdparty/lua/lzio.h \
    ../../../luna2d/utils/lunacolor.h \
    ../../../luna2d/utils/lunaindexlist.h \
	../../../luna2d/assets/lunaassets.h \
    ../../../luna2d/lunaengine.h \
    ../../../luna2d/lunascenes.h \
    ../../../luna2d/lunaconstants.h \
    ../../../luna2d/lunaconfig.h \
    ../../../luna2d/lunasizes.h \
    ../../../luna2d/graphics/lunatextureregion.h \
    ../../../luna2d/graphics/lunatextureatlas.h \
    ../../../luna2d/graphics/lunasprite.h \
    ../../../luna2d/thirdparty/json11/json11.hpp \
    ../../../luna2d/utils/lunawatcher.h \
    ../../../luna2d/lua/luadynamictype.h \
    ../../../luna2d/graphics/lunamesh.h \
    ../../../luna2d/thirdparty/Box2D/Collision/Shapes/b2ChainShape.h \
    ../../../luna2d/thirdparty/Box2D/Collision/Shapes/b2CircleShape.h \
    ../../../luna2d/thirdparty/Box2D/Collision/Shapes/b2EdgeShape.h \
    ../../../luna2d/thirdparty/Box2D/Collision/Shapes/b2PolygonShape.h \
    ../../../luna2d/thirdparty/Box2D/Collision/Shapes/b2Shape.h \
    ../../../luna2d/thirdparty/Box2D/Collision/b2BroadPhase.h \
    ../../../luna2d/thirdparty/Box2D/Collision/b2Collision.h \
    ../../../luna2d/thirdparty/Box2D/Collision/b2Distance.h \
    ../../../luna2d/thirdparty/Box2D/Collision/b2DynamicTree.h \
    ../../../luna2d/thirdparty/Box2D/Collision/b2TimeOfImpact.h \
    ../../../luna2d/thirdparty/Box2D/Common/b2BlockAllocator.h \
    ../../../luna2d/thirdparty/Box2D/Common/b2Draw.h \
    ../../../luna2d/thirdparty/Box2D/Common/b2GrowableStack.h \
    ../../../luna2d/thirdparty/Box2D/Common/b2Math.h \
    ../../../luna2d/thirdparty/Box2D/Common/b2Settings.h \
    ../../../luna2d/thirdparty/Box2D/Common/b2StackAllocator.h \
    ../../../luna2d/thirdparty/Box2D/Common/b2Timer.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2Contact.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2GearJoint.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2Joint.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/b2Body.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/b2ContactManager.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/b2Fixture.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/b2Island.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/b2TimeStep.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/b2World.h \
    ../../../luna2d/thirdparty/Box2D/Dynamics/b2WorldCallbacks.h \
    ../../../luna2d/thirdparty/Box2D/Rope/b2Rope.h \
    ../../../luna2d/thirdparty/Box2D/Box2D.h \
    ../../../luna2d/lua/luanil.h \
    ../../../luna2d/lua/luaobject.h \
    ../../../luna2d/physics/lunaphysicsmodule.h \
    ../../../luna2d/physics/lunaphysicsworld.h \
    ../../../luna2d/physics/lunaphysicsbody.h \
    ../../../luna2d/physics/lunaphysicsfixture.h \
    ../../../luna2d/utils/lunamakeweak.h \
    ../../../luna2d/physics/lunaphysicsdebugrenderer.h \
    ../../../luna2d/graphics/shaders/primitives.vert.h \
    ../../../luna2d/utils/lunaglhelpers.h \
	../../../luna2d/utils/lunamacro.h \
    ../../../luna2d/physics/shapes/lunaphysicscircleshape.h \
    ../../../luna2d/physics/shapes/lunaphysicsedgeshape.h \
    ../../../luna2d/physics/shapes/lunaphysicsrectshape.h \
    ../../../luna2d/physics/shapes/lunaphysicsshape.h \
    ../../../luna2d/physics/joints/lunaphysicsjoint.h \
    ../../../luna2d/physics/joints/lunaphysicsdistancejoint.h \
    ../../../luna2d/physics/lunaphysicsutils.h \
    ../../../luna2d/platform/qt/lunaqtfiles.h \
    ../../../luna2d/platform/qt/lunaqtlog.h \
    ../../../luna2d/platform/qt/lunaqtgl.h \
    ../../../luna2d/platform/qt/lunaqtutils.h \
    ../../../luna2d/graphics/lunacurverenderer.h \
    ../../../luna2d/lua/luaptr.h \
    ../../../luna2d/assets/lunatextureloader.h \
    ../../../luna2d/assets/lunatextureatlasloader.h \
    ../../../luna2d/lua/scripts/chancetable.lua.h \
    ../../../luna2d/lunabindings.h \
    ../../../luna2d/utils/math/lunaintersect.h \
    ../../../luna2d/utils/math/lunasplines.h \
    ../../../luna2d/utils/math/lunavector2.h \
    ../../../luna2d/utils/math/lunamath.h \
    ../../../luna2d/utils/math/lunaglm.h \
    ../../../luna2d/lunadebug.h \
    ../../../luna2d/graphics/lunatext.h \
    ../../../luna2d/graphics/lunafont.h \
    ../../../luna2d/assets/lunafontloader.h \
	../../../luna2d/graphics/lunafontgenerator.h \
    ../../../luna2d/thirdparty/freetype/devel/ft2build.h \
    ../../../luna2d/thirdparty/freetype/devel/ftoption.h \
    ../../../luna2d/thirdparty/freetype/include/config/ftconfig.h \
    ../../../luna2d/thirdparty/freetype/include/config/ftheader.h \
    ../../../luna2d/thirdparty/freetype/include/config/ftmodule.h \
    ../../../luna2d/thirdparty/freetype/include/config/ftoption.h \
    ../../../luna2d/thirdparty/freetype/include/config/ftstdlib.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svbdf.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svcid.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svgldict.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svgxval.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svkern.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svmm.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svotval.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svpfr.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svpostnm.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svprop.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svpscmap.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svpsinfo.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svsfnt.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svttcmap.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svtteng.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svttglyf.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svwinfnt.h \
    ../../../luna2d/thirdparty/freetype/include/internal/services/svxf86nm.h \
    ../../../luna2d/thirdparty/freetype/include/internal/autohint.h \
    ../../../luna2d/thirdparty/freetype/include/internal/ftcalc.h \
    ../../../luna2d/thirdparty/freetype/include/internal/ftdebug.h \
    ../../../luna2d/thirdparty/freetype/include/internal/ftdriver.h \
    ../../../luna2d/thirdparty/freetype/include/internal/ftgloadr.h \
    ../../../luna2d/thirdparty/freetype/include/internal/ftmemory.h \
    ../../../luna2d/thirdparty/freetype/include/internal/ftobjs.h \
    ../../../luna2d/thirdparty/freetype/include/internal/ftpic.h \
    ../../../luna2d/thirdparty/freetype/include/internal/ftrfork.h \
    ../../../luna2d/thirdparty/freetype/include/internal/ftserv.h \
    ../../../luna2d/thirdparty/freetype/include/internal/ftstream.h \
    ../../../luna2d/thirdparty/freetype/include/internal/fttrace.h \
    ../../../luna2d/thirdparty/freetype/include/internal/ftvalid.h \
    ../../../luna2d/thirdparty/freetype/include/internal/internal.h \
    ../../../luna2d/thirdparty/freetype/include/internal/psaux.h \
    ../../../luna2d/thirdparty/freetype/include/internal/pshints.h \
    ../../../luna2d/thirdparty/freetype/include/internal/sfnt.h \
    ../../../luna2d/thirdparty/freetype/include/internal/t1types.h \
    ../../../luna2d/thirdparty/freetype/include/internal/tttypes.h \
    ../../../luna2d/thirdparty/freetype/include/freetype.h \
    ../../../luna2d/thirdparty/freetype/include/ft2build.h \
    ../../../luna2d/thirdparty/freetype/include/ftadvanc.h \
    ../../../luna2d/thirdparty/freetype/include/ftautoh.h \
    ../../../luna2d/thirdparty/freetype/include/ftbbox.h \
    ../../../luna2d/thirdparty/freetype/include/ftbdf.h \
    ../../../luna2d/thirdparty/freetype/include/ftbitmap.h \
    ../../../luna2d/thirdparty/freetype/include/ftbzip2.h \
    ../../../luna2d/thirdparty/freetype/include/ftcache.h \
    ../../../luna2d/thirdparty/freetype/include/ftcffdrv.h \
    ../../../luna2d/thirdparty/freetype/include/ftchapters.h \
    ../../../luna2d/thirdparty/freetype/include/ftcid.h \
    ../../../luna2d/thirdparty/freetype/include/fterrdef.h \
    ../../../luna2d/thirdparty/freetype/include/fterrors.h \
    ../../../luna2d/thirdparty/freetype/include/ftgasp.h \
    ../../../luna2d/thirdparty/freetype/include/ftglyph.h \
    ../../../luna2d/thirdparty/freetype/include/ftgxval.h \
    ../../../luna2d/thirdparty/freetype/include/ftgzip.h \
    ../../../luna2d/thirdparty/freetype/include/ftimage.h \
    ../../../luna2d/thirdparty/freetype/include/ftincrem.h \
    ../../../luna2d/thirdparty/freetype/include/ftlcdfil.h \
    ../../../luna2d/thirdparty/freetype/include/ftlist.h \
    ../../../luna2d/thirdparty/freetype/include/ftlzw.h \
    ../../../luna2d/thirdparty/freetype/include/ftmac.h \
    ../../../luna2d/thirdparty/freetype/include/ftmm.h \
    ../../../luna2d/thirdparty/freetype/include/ftmodapi.h \
    ../../../luna2d/thirdparty/freetype/include/ftmoderr.h \
    ../../../luna2d/thirdparty/freetype/include/ftotval.h \
    ../../../luna2d/thirdparty/freetype/include/ftoutln.h \
    ../../../luna2d/thirdparty/freetype/include/ftpfr.h \
    ../../../luna2d/thirdparty/freetype/include/ftrender.h \
    ../../../luna2d/thirdparty/freetype/include/ftsizes.h \
    ../../../luna2d/thirdparty/freetype/include/ftsnames.h \
    ../../../luna2d/thirdparty/freetype/include/ftstroke.h \
    ../../../luna2d/thirdparty/freetype/include/ftsynth.h \
    ../../../luna2d/thirdparty/freetype/include/ftsystem.h \
    ../../../luna2d/thirdparty/freetype/include/fttrigon.h \
    ../../../luna2d/thirdparty/freetype/include/ftttdrv.h \
    ../../../luna2d/thirdparty/freetype/include/fttypes.h \
    ../../../luna2d/thirdparty/freetype/include/ftwinfnt.h \
    ../../../luna2d/thirdparty/freetype/include/ftxf86.h \
    ../../../luna2d/thirdparty/freetype/include/t1tables.h \
    ../../../luna2d/thirdparty/freetype/include/ttnameid.h \
    ../../../luna2d/thirdparty/freetype/include/tttables.h \
    ../../../luna2d/thirdparty/freetype/include/tttags.h \
    ../../../luna2d/thirdparty/freetype/include/ttunpat.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afangles.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afblue.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afcjk.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afcover.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afdummy.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/aferrors.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afglobal.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afhints.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afindic.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/aflatin.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/aflatin2.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afloader.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afmodule.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afpic.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afranges.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afscript.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afstyles.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/aftypes.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afwarp.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/afwrtsys.h \
    ../../../luna2d/thirdparty/freetype/src/autofit/hbshim.h \
    ../../../luna2d/thirdparty/freetype/src/base/basepic.h \
    ../../../luna2d/thirdparty/freetype/src/base/ftbase.h \
    ../../../luna2d/thirdparty/freetype/src/base/md5.h \
    ../../../luna2d/thirdparty/freetype/src/bdf/bdf.h \
    ../../../luna2d/thirdparty/freetype/src/bdf/bdfdrivr.h \
    ../../../luna2d/thirdparty/freetype/src/bdf/bdferror.h \
    ../../../luna2d/thirdparty/freetype/src/cache/ftccache.h \
    ../../../luna2d/thirdparty/freetype/src/cache/ftccback.h \
    ../../../luna2d/thirdparty/freetype/src/cache/ftcerror.h \
    ../../../luna2d/thirdparty/freetype/src/cache/ftcglyph.h \
    ../../../luna2d/thirdparty/freetype/src/cache/ftcimage.h \
    ../../../luna2d/thirdparty/freetype/src/cache/ftcmanag.h \
    ../../../luna2d/thirdparty/freetype/src/cache/ftcmru.h \
    ../../../luna2d/thirdparty/freetype/src/cache/ftcsbits.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2arrst.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2blues.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2error.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2fixed.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2font.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2ft.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2glue.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2hints.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2intrp.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2read.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2stack.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cf2types.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cffcmap.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cffdrivr.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cfferrs.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cffgload.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cffload.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cffobjs.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cffparse.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cffpic.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cfftoken.h \
    ../../../luna2d/thirdparty/freetype/src/cff/cfftypes.h \
    ../../../luna2d/thirdparty/freetype/src/cid/ciderrs.h \
    ../../../luna2d/thirdparty/freetype/src/cid/cidgload.h \
    ../../../luna2d/thirdparty/freetype/src/cid/cidload.h \
    ../../../luna2d/thirdparty/freetype/src/cid/cidobjs.h \
    ../../../luna2d/thirdparty/freetype/src/cid/cidparse.h \
    ../../../luna2d/thirdparty/freetype/src/cid/cidriver.h \
    ../../../luna2d/thirdparty/freetype/src/cid/cidtoken.h \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvalid.h \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvcommn.h \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxverror.h \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvfeat.h \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmod.h \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmort.h \
    ../../../luna2d/thirdparty/freetype/src/gxvalid/gxvmorx.h \
    ../../../luna2d/thirdparty/freetype/src/gzip/infblock.h \
    ../../../luna2d/thirdparty/freetype/src/gzip/infcodes.h \
    ../../../luna2d/thirdparty/freetype/src/gzip/inffixed.h \
    ../../../luna2d/thirdparty/freetype/src/gzip/inftrees.h \
    ../../../luna2d/thirdparty/freetype/src/gzip/infutil.h \
    ../../../luna2d/thirdparty/freetype/src/gzip/zconf.h \
    ../../../luna2d/thirdparty/freetype/src/gzip/zlib.h \
    ../../../luna2d/thirdparty/freetype/src/gzip/zutil.h \
    ../../../luna2d/thirdparty/freetype/src/lzw/ftzopen.h \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otvalid.h \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otvcommn.h \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otverror.h \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otvgpos.h \
    ../../../luna2d/thirdparty/freetype/src/otvalid/otvmod.h \
    ../../../luna2d/thirdparty/freetype/src/pcf/pcf.h \
    ../../../luna2d/thirdparty/freetype/src/pcf/pcfdrivr.h \
    ../../../luna2d/thirdparty/freetype/src/pcf/pcferror.h \
    ../../../luna2d/thirdparty/freetype/src/pcf/pcfread.h \
    ../../../luna2d/thirdparty/freetype/src/pcf/pcfutil.h \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrcmap.h \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrdrivr.h \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrerror.h \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrgload.h \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrload.h \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrobjs.h \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrsbit.h \
    ../../../luna2d/thirdparty/freetype/src/pfr/pfrtypes.h \
    ../../../luna2d/thirdparty/freetype/src/psaux/afmparse.h \
    ../../../luna2d/thirdparty/freetype/src/psaux/psauxerr.h \
    ../../../luna2d/thirdparty/freetype/src/psaux/psauxmod.h \
    ../../../luna2d/thirdparty/freetype/src/psaux/psconv.h \
    ../../../luna2d/thirdparty/freetype/src/psaux/psobjs.h \
    ../../../luna2d/thirdparty/freetype/src/psaux/t1cmap.h \
    ../../../luna2d/thirdparty/freetype/src/psaux/t1decode.h \
    ../../../luna2d/thirdparty/freetype/src/pshinter/pshalgo.h \
    ../../../luna2d/thirdparty/freetype/src/pshinter/pshglob.h \
    ../../../luna2d/thirdparty/freetype/src/pshinter/pshmod.h \
    ../../../luna2d/thirdparty/freetype/src/pshinter/pshnterr.h \
    ../../../luna2d/thirdparty/freetype/src/pshinter/pshpic.h \
    ../../../luna2d/thirdparty/freetype/src/pshinter/pshrec.h \
    ../../../luna2d/thirdparty/freetype/src/psnames/psmodule.h \
    ../../../luna2d/thirdparty/freetype/src/psnames/psnamerr.h \
    ../../../luna2d/thirdparty/freetype/src/psnames/pspic.h \
    ../../../luna2d/thirdparty/freetype/src/psnames/pstables.h \
    ../../../luna2d/thirdparty/freetype/src/raster/ftmisc.h \
    ../../../luna2d/thirdparty/freetype/src/raster/ftraster.h \
    ../../../luna2d/thirdparty/freetype/src/raster/ftrend1.h \
    ../../../luna2d/thirdparty/freetype/src/raster/rasterrs.h \
    ../../../luna2d/thirdparty/freetype/src/raster/rastpic.h \
    ../../../luna2d/thirdparty/freetype/src/sfnt/pngshim.h \
    ../../../luna2d/thirdparty/freetype/src/sfnt/sfdriver.h \
    ../../../luna2d/thirdparty/freetype/src/sfnt/sferrors.h \
    ../../../luna2d/thirdparty/freetype/src/sfnt/sfntpic.h \
    ../../../luna2d/thirdparty/freetype/src/sfnt/sfobjs.h \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttbdf.h \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttcmap.h \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttcmapc.h \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttkern.h \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttload.h \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttmtx.h \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttpost.h \
    ../../../luna2d/thirdparty/freetype/src/sfnt/ttsbit.h \
    ../../../luna2d/thirdparty/freetype/src/smooth/ftgrays.h \
    ../../../luna2d/thirdparty/freetype/src/smooth/ftsmerrs.h \
    ../../../luna2d/thirdparty/freetype/src/smooth/ftsmooth.h \
    ../../../luna2d/thirdparty/freetype/src/smooth/ftspic.h \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttdriver.h \
    ../../../luna2d/thirdparty/freetype/src/truetype/tterrors.h \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttgload.h \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttgxvar.h \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttinterp.h \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttobjs.h \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttpic.h \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttpload.h \
    ../../../luna2d/thirdparty/freetype/src/truetype/ttsubpix.h \
    ../../../luna2d/thirdparty/freetype/src/type1/t1afm.h \
    ../../../luna2d/thirdparty/freetype/src/type1/t1driver.h \
    ../../../luna2d/thirdparty/freetype/src/type1/t1errors.h \
    ../../../luna2d/thirdparty/freetype/src/type1/t1gload.h \
    ../../../luna2d/thirdparty/freetype/src/type1/t1load.h \
    ../../../luna2d/thirdparty/freetype/src/type1/t1objs.h \
    ../../../luna2d/thirdparty/freetype/src/type1/t1parse.h \
    ../../../luna2d/thirdparty/freetype/src/type1/t1tokens.h \
    ../../../luna2d/thirdparty/freetype/src/type42/t42drivr.h \
    ../../../luna2d/thirdparty/freetype/src/type42/t42error.h \
    ../../../luna2d/thirdparty/freetype/src/type42/t42objs.h \
    ../../../luna2d/thirdparty/freetype/src/type42/t42parse.h \
    ../../../luna2d/thirdparty/freetype/src/type42/t42types.h \
    ../../../luna2d/thirdparty/freetype/src/winfonts/fnterrs.h \
    ../../../luna2d/thirdparty/freetype/src/winfonts/winfnt.h \
    ../../../luna2d/thirdparty/utf8cpp/utf8/checked.h \
    ../../../luna2d/thirdparty/utf8cpp/utf8/core.h \
    ../../../luna2d/thirdparty/utf8cpp/utf8/unchecked.h \
    ../../../luna2d/thirdparty/utf8cpp/utf8.h \
    ../../../luna2d/utils/lunautf.h \
    ../../../luna2d/platform/lunaprefs.h \
    ../../../luna2d/platform/qt/lunaqtprefs.h

QMAKE_MAC_SDK = macosx10.9
